{{- if .Values.collectorFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sql-exporter.fullname" . }}
  labels:
    {{- include "sql-exporter.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.collectorFiles }}
  {{ $k }}: |-
    {{- if typeIsLike "string" $v -}}
    {{- $v = (tpl $v $ | fromYaml) -}}
    {{- end -}}
    {{- tpl (toYaml $v) $ | nindent 4}}
  {{- end}}
{{- end }}
