# ---------------------------------------------------------------------
# -- This secret holds the config file of sql_exporter
# ---------------------------------------------------------------------
{{- if .Values.createConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sql-exporter.fullname" . }}
  labels:
    {{- include "sql-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  sql_exporter.yml: |-
    {{- $conf := "" -}}
    {{- if typeIsLike "string" .Values.config -}}
    {{- $conf = (tpl .Values.config . | fromYaml) -}}
    {{- else -}}
    {{- $conf = .Values.config -}}
    {{- end -}}
    {{- tpl (toYaml $conf) . | nindent 4 }} 
{{- end }}
